"""Homeowner-friendly, renovation-specific input definitions.

The flow is intentionally two-stage: select the work first, then collect
existing quantities and the quantities that will actually be repaired,
replaced, renewed, or added. Existing quantities are context only; only the
work quantity is costed.
"""

WORK_INPUTS = {
    "Painting": [
        ("Painting surfaces", "painting_surfaces", "multi", ["Walls", "Ceiling", "Exterior wall"]),
        ("Existing wall paint area (sq ft)", "existing_painting_wall_area", "number", 0),
        ("Wall area to repaint (sq ft)", "painting_wall_area", "number", 0),
        ("Existing ceiling paint area (sq ft)", "existing_painting_ceiling_area", "number", 0),
        ("Ceiling area to repaint (sq ft)", "painting_ceiling_area", "number", 0),
        ("Existing exterior wall paint area (sq ft)", "existing_painting_exterior_area", "number", 0),
        ("Exterior wall area to repaint (sq ft)", "painting_exterior_area", "number", 0),
        ("Surface condition", "surface_condition", "select", ["Good", "Minor cracks", "Major repair"]),
    ],
    "Flooring & Tiling": [
        ("Flooring work included", "flooring_work", "multi", ["New flooring / tile installation", "Floor replacement", "Floor repair"]),
        ("Existing floor area (sq ft)", "existing_flooring_area", "number", 0),
        ("Floor area to install / replace (sq ft)", "flooring_work_area", "number", 0),
        ("Floor repair level", "floor_repair", "select", ["Minor", "Major"]),
    ],
    "Plumbing": [
        ("Plumbing work location", "plumbing_location", "multi", ["Bathroom", "Kitchen", "Whole House", "Multiple Areas"]),
        ("Plumbing work included", "plumbing_work", "multi", ["Pipe replacement", "New pipe installation", "Leakage repair", "Drainage work", "Fixture replacement", "Water tank connection"]),
        ("Existing plumbing pipe length (metres)", "existing_plumbing_pipe_length_m", "number", 0),
        ("Pipe length to replace / install (metres)", "plumbing_pipe_length_m", "number", 0),
        ("Active leak points (number)", "plumbing_leak_count", "number", 0),
        ("Existing toilets (number)", "existing_plumbing_toilet_count", "number", 0),
        ("Toilets to replace / add (number)", "plumbing_toilet_count", "number", 0),
        ("Existing wash basins (number)", "existing_plumbing_basin_count", "number", 0),
        ("Wash basins to replace / add (number)", "plumbing_basin_count", "number", 0),
        ("Existing showers (number)", "existing_plumbing_shower_count", "number", 0),
        ("Showers to replace / add (number)", "plumbing_shower_count", "number", 0),
        ("Existing taps / faucets (number)", "existing_plumbing_tap_count", "number", 0),
        ("Taps / faucets to replace / add (number)", "plumbing_tap_count", "number", 0),
        ("Existing water tanks (number)", "existing_plumbing_tank_count", "number", 0),
        ("Water tanks to connect (number)", "plumbing_tank_count", "number", 0),
    ],
    "Electrical Work": [
        ("Electrical areas", "electrical_areas", "multi", ["Bedrooms", "Living room", "Kitchen", "Bathrooms", "Other areas"]),
        ("Electrical work included", "electrical_work", "multi", ["Complete rewiring", "New switches", "New socket points", "Lighting", "Fan points", "Distribution board"]),
        ("Existing switch points (number)", "existing_switch_points", "number", 0),
        ("Switch points to replace / add (number)", "switch_points", "number", 0),
        ("Existing socket points (number)", "existing_socket_points", "number", 0),
        ("Socket points to replace / add (number)", "socket_points", "number", 0),
        ("Existing light points (number)", "existing_light_points", "number", 0),
        ("Light points to replace / add (number)", "light_points", "number", 0),
        ("Existing fan points (number)", "existing_fan_points", "number", 0),
        ("Fan points to replace / add (number)", "fan_points", "number", 0),
        ("Existing cable length (metres)", "existing_electrical_cable_length_m", "number", 0),
        ("Cable length to replace / rewire (metres)", "electrical_cable_length_m", "number", 0),
        ("Existing distribution boards (number)", "existing_distribution_board_count", "number", 0),
        ("Distribution boards to replace / add (number)", "distribution_board_count", "number", 0),
    ],
    "Kitchen Renovation": [
        ("Kitchen work included", "kitchen_work", "multi", ["Cabinet work", "Countertop", "Sink", "Plumbing", "Electrical", "Backsplash"]),
        ("Existing cupboard / cabinet units (number)", "existing_cupboards", "number", 0),
        ("Cupboard / cabinet units to replace / add (number)", "additional_cupboards", "number", 0),
        ("Existing countertop area (sq ft)", "existing_countertop_area", "number", 0),
        ("Countertop area to replace / add (sq ft)", "additional_countertop_area", "number", 0),
        ("Existing sinks (number)", "existing_kitchen_sink_count", "number", 0),
        ("Sinks to replace / add (number)", "kitchen_sink_count", "number", 0),
        ("Existing backsplash area (sq ft)", "existing_kitchen_backsplash_area", "number", 0),
        ("Backsplash area to replace / add (sq ft)", "kitchen_backsplash_area", "number", 0),
        ("Existing kitchen electrical points (number)", "existing_kitchen_electrical_points", "number", 0),
        ("Kitchen electrical points to replace / add (number)", "kitchen_electrical_points", "number", 0),
        ("Existing kitchen plumbing points (number)", "existing_kitchen_plumbing_points", "number", 0),
        ("Kitchen plumbing points to replace / add (number)", "kitchen_plumbing_points", "number", 0),
    ],
    "Bathroom Renovation": [
        ("Bathroom work included", "bathroom_work", "multi", ["Floor tiles", "Wall tiles", "Toilet", "Wash basin", "Shower", "Plumbing", "Waterproofing"]),
        ("Existing bathroom floor tile area (sq ft)", "existing_bathroom_floor_area", "number", 0),
        ("Floor tile area to replace / install (sq ft)", "bathroom_floor_area", "number", 0),
        ("Existing wall tile area (sq ft)", "existing_bathroom_wall_tile_area", "number", 0),
        ("Wall tile area to replace / install (sq ft)", "bathroom_wall_tile_area", "number", 0),
        ("Existing toilets (number)", "existing_bathroom_toilet_count", "number", 0),
        ("Toilets to replace / add (number)", "bathroom_toilet_count", "number", 0),
        ("Existing wash basins (number)", "existing_bathroom_basin_count", "number", 0),
        ("Wash basins to replace / add (number)", "bathroom_basin_count", "number", 0),
        ("Existing showers (number)", "existing_bathroom_shower_count", "number", 0),
        ("Showers to replace / add (number)", "bathroom_shower_count", "number", 0),
        ("Existing bathroom pipe length (metres)", "existing_bathroom_pipe_length_m", "number", 0),
        ("Pipe length to replace / install (metres)", "bathroom_pipe_length_m", "number", 0),
        ("Existing waterproofed area (sq ft)", "existing_bathroom_waterproof_area", "number", 0),
        ("Waterproofing area to renew / add (sq ft)", "bathroom_waterproof_area", "number", 0),
    ],
    "Roofing": [
        ("Roof work included", "roof_work", "multi", ["Crack repair", "Leakage repair", "Tile replacement", "Concrete repair", "Complete roof replacement"]),
        ("Existing roof area (sq ft)", "existing_roof_area", "number", 0),
        ("Roof area to repair / replace (sq ft)", "roof_work_area", "number", 0),
        ("Existing roof tile area (sq ft)", "existing_roof_tile_area", "number", 0),
        ("Roof tile area to replace (sq ft)", "roof_tile_replacement_area", "number", 0),
        ("Existing concrete repair area (sq ft)", "existing_roof_concrete_repair_area", "number", 0),
        ("Concrete repair area (sq ft)", "roof_concrete_repair_area", "number", 0),
        ("Existing waterproofed roof area (sq ft)", "existing_roof_waterproof_area", "number", 0),
        ("Roof waterproofing area to renew / add (sq ft)", "roof_waterproof_area", "number", 0),
        ("Roof type", "roof_type", "select", ["Concrete", "Tile", "Metal sheet"]),
    ],
    "Interior Renovation": [
        ("Interior work included", "interior_work", "multi", ["False ceiling", "Wardrobe / Storage", "Wall work", "Partition", "Flooring", "Painting", "Plumbing", "Electrical", "Carpentry / Other interior work"]),
        ("Existing false ceiling area (sq ft)", "existing_false_ceiling_area", "number", 0),
        ("False ceiling area to install / replace (sq ft)", "false_ceiling_area", "number", 0),
        ("Existing wardrobe / storage units (number)", "existing_wardrobe_count", "number", 0),
        ("Wardrobe / storage units to replace / add (number)", "wardrobe_count", "number", 0),
        ("Existing wall / partition work area (sq ft)", "existing_partition_area", "number", 0),
        ("Wall / partition area to repair / build (sq ft)", "partition_area", "number", 0),
        ("Existing interior flooring area (sq ft)", "existing_interior_flooring_area", "number", 0),
        ("Interior flooring area to replace / install (sq ft)", "interior_flooring_area", "number", 0),
        ("Existing interior painted area (sq ft)", "existing_interior_painting_area", "number", 0),
        ("Interior painting area to repaint (sq ft)", "interior_painting_area", "number", 0),
        ("Existing interior electrical points (number)", "existing_interior_electrical_points", "number", 0),
        ("Interior electrical points to replace / add (number)", "interior_electrical_points", "number", 0),
        ("Existing interior plumbing points (number)", "existing_interior_plumbing_points", "number", 0),
        ("Interior plumbing points to replace / add (number)", "interior_plumbing_points", "number", 0),
    ],
    "Exterior Renovation": [
        ("Exterior work included", "exterior_work", "multi", ["Crack repair", "Plaster repair", "Painting", "Waterproofing", "Compound wall / Gate"]),
        ("Existing exterior repair / plaster area (sq ft)", "existing_exterior_repair_area", "number", 0),
        ("Repair / plaster area to work on (sq ft)", "exterior_repair_area", "number", 0),
        ("Existing exterior painted area (sq ft)", "existing_exterior_painting_area", "number", 0),
        ("Exterior painting area to repaint (sq ft)", "exterior_painting_area", "number", 0),
        ("Existing waterproofed exterior area (sq ft)", "existing_exterior_waterproof_area", "number", 0),
        ("Exterior waterproofing area to renew / add (sq ft)", "exterior_waterproof_area", "number", 0),
        ("Existing compound wall / gate length (ft)", "existing_compound_wall_gate_length_ft", "number", 0),
        ("Compound wall / gate length to repair / build (ft)", "compound_wall_gate_length_ft", "number", 0),
    ],
}

FULL_COMPONENT_TO_WORK = {
    "Wall / structural repair": "Exterior Renovation", "Roofing": "Roofing", "Plumbing": "Plumbing",
    "Electrical work": "Electrical Work", "Flooring & tiling": "Flooring & Tiling", "Painting": "Painting",
    "Kitchen": "Kitchen Renovation", "Bathroom": "Bathroom Renovation", "Exterior work": "Exterior Renovation"
}

def fields_for(renovation):
    return WORK_INPUTS.get(renovation, [])
